# Global parameters for data analysis.

# D I R E C T O R I E S
# -------------------------------------------
# Data folder
DATA_FOLDER : "/home/marcial/detdaq/3005241000-Ti10Al60_LO/20240603_Dark_Data_Auto/"
# Project name
PROJECT_NAME : ""
# Project folder
PROJECT_FOLDER : ""

# E X P E R I M E N T   P A R A M S
# -------------------------------------------
# No defined additional attenuations
IN_ADD_ATT : 0
OUT_ADD_ATT : 0

# Pre-overdriven attenuations. 
# Previous attenuation to the overdriven point
ATT_OVRDRN : []

# D E T E C T O R   P R O P E R T I E S
# -------------------------------------------
MATERIAL : 'Al'
DIMENSIONS : [45e-3, 2, 2482] # [um, um, um]
